export interface Expediente{
    idExpe: "",
    ruc:"",
    fechaIngresoMP: "",
    fechaSGDC: "",
    fechaRecepcion: "",
    fechaRecepcionLF: "",
    fechaLimiteInspeccion: "",
    numeroInforme: "",
    estado: "",
    fecha: "",
    hora: "",
    inspectores: "",
    ilo: "",
}